image: gitpod/workspace-python-3.11

tasks:
    - name: Setup
      before: start.sh pcloud caddy
      init: task setup
      command: |
        source .venv/bin/activate
        task dev-server

ports:
    - port: 20711
      name: Caddy
      onOpen: open-browser
      description: Caddy
      visibility: private
      protocol: https