image: ghcr.io/esperoj/esperoj-dev

tasks:
    - name: Setup
      before: |
        chezmoi init --apply --force
      init: |
        echo $(date --utc) > ~/init.txt
      command: |
        source ~/.profile
        source .venv/bin/activate
        start.sh pcloud caddy
        task dev-server

ports:
    - port: 20711
      name: Caddy
      onOpen: open-browser
      description: Caddy
      visibility: private
      protocol: https