image: ghcr.io/esperoj/esperoj-dev

tasks:
    - name: Setup
      before: |
        chezmoi init --apply --force
        chezmoi update --force
        source ~/.profile
        start.sh pcloud caddy
      init: task setup
      command: |
        source ~/.profile
        source .venv/bin/activate
        task dev-server

ports:
    - port: 20711
      name: Caddy
      onOpen: open-browser
      description: Caddy
      visibility: private
      protocol: https