[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
authors = [
  {name = "Esperoj", email = "esperoj@esperoj.eu.org"}
]
description = "This is my personal package used to automate the boring stuffs."
license = {text = "GPLv3"}
name = "esperoj"
version = "0.13.5"
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
  "boto3>=1.35.10",
  "seatable-api>=2.6.11",
  "requests>=2.32.3",
  "py7zr>=0.21.0"
]

[project.optional-dependencies]
cli = ["click"]
api = ["litestar"]
server = ["litestar[standard]"]

[project.scripts]
esperoj = "esperoj.__main__:cli"

[project.urls]
Changelog = "https://github.com/esperoj/esperoj/releases/"
Documentation = "https://www.esperoj.eu.org/docs/"
Homepage = "https://www.esperoj.eu.org/"
"Issue Tracker" = "https://github.com/esperoj/esperoj/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
Repository = "https://github.com/esperoj/esperoj"

[tool.coverage.report]
precision = 1
show_missing = true
skip_covered = true

[tool.coverage.run]
concurrency = ["multiprocessing", "thread"]
omit = ["*/tests/*"]
parallel = true
source = ["esperoj"]

[tool.pyright]
pythonVersion = "3.11"
# typeCheckingMode = "standard"
include = ["esperoj"]
exclude = ["**/node_modules",
    "**/__pycache__"
]

[tool.pytest.ini_options]
addopts = "--verbose --cov-report term --cov=esperoj --color=yes --exitfirst --failed-first"
testpaths = ["tests"]
xfail_strict = true
markers = [
  "only: run this only"
]

[tool.ruff]
fix = true
lint.select = [
  "A", # flake8-builtins
  "B", # flake8-bugbear
  "BLE", # flake8-blind-except
  "C4", # flake8-comprehensions
  "C90", # mccabe
  "D", # pydocstyle
  "DJ", # flake8-django
  "DTZ", # flake8-datetimez
  "E", # pycodestyle errors
  "ERA", # eradicate
  "EXE", # flake8-executable
  "F", # pyflakes
  "G", # flake8-logging-format
  "I", # isort
  "ICN", # flake8-import-conventions
  "ISC", # flake8-implicit-str-concat
  "N", # pep8-naming
  "PIE", # flake8-pie
  "PLC", # pylint - convention
  "PLE", # pylint - error
  "PLW", # pylint - warning
  "PTH", # flake8-use-pathlib
  "Q", # flake8-quotes
  "RET", # flake8-return
  "RUF", # Ruff-specific rules
  "S", # flake8-bandit
  "SIM", # flake8-simplify
  "T10", # flake8-debugger
  "T20", # flake8-print
  "TCH", # flake8-type-checking
  "TID", # flake8-tidy-imports
  "UP", # pyupgrade
  "W", # pycodestyle - warning
  "YTT", # flake8-2020
]

line-length = 120
lint.ignore = [
  "S608", # Possible SQL injection
  "A003", # flake8-builtins - class attribute {name} is shadowing a python builtin
  "B010", # flake8-bugbear - do not call setattr with a constant attribute value
  "D100", # pydocstyle - missing docstring in public module
  "D101", # pydocstyle - missing docstring in public class
  "D102", # pydocstyle - missing docstring in public method
  "D103", # pydocstyle - missing docstring in public function
  "D104", # pydocstyle - missing docstring in public package
  "D105", # pydocstyle - missing docstring in magic method
  "D106", # pydocstyle - missing docstring in public nested class
  "D107", # pydocstyle - missing docstring in __init__
  "D202", # pydocstyle - no blank lines allowed after function docstring
  "D205", # pydocstyle - 1 blank line required between summary line and description
  "D415", # pydocstyle - first line should end with a period, question mark, or exclamation point
  "E501", # pycodestyle line too long, handled by ruff format
  "PLW2901", # pylint - for loop variable overwritten by assignment target
  "RUF012", # Ruff-specific rule - annotated with classvar
  "ISC001", # Ruff formatter incompatible
  "S603", # Check shell input
  "S607", # Starting a process with a partial executable path
  "C901", # `function` is too complex
  "BLE001", # Do not catch blind exception: `Exception`
  "G004", # Logging statement uses f-string
]
src = ["esperoj", "tests"]
target-version = "py311"
exclude = [
    "typings"
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 12

[tool.ruff.lint.isort]
known-first-party = ["esperoj"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.*" = [
  "A",
  "ARG",
  "B",
  "BLE",
  "C901",
  "D",
  "DTZ",
  "EM",
  "FBT",
  "G",
  "N",
  "PGH",
  "PIE",
  "PLR",
  "PLW",
  "PTH",
  "RSE",
  "S",
  "S101",
  "SIM",
  "TCH",
  "TRY",
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 88
