"""
This type stub file was generated by pyright.
"""

import sys

is_cloud = ...
if is_cloud and not sys.stdin.isatty():
    context_data = ...
    context_data = ...
else:
    context_data = ...

def need_data(func):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any | None]:
    ...

class Context:
    @property
    def server_url(self):  # -> str | None:
        ...
    @property
    def api_token(self):  # -> str | None:
        ...
    @property
    @need_data
    def current_row(self):  # -> Any:
        ...
    @property
    @need_data
    def current_table(self):  # -> Any:
        ...
    @property
    @need_data
    def current_user_id(self):  # -> Any:
        ...
    @property
    @need_data
    def current_username(self):  # -> Any:
        ...
    @property
    @need_data
    def current_id_in_org(self):  # -> Any:
        ...
    @need_data
    def get_setting_by_key(self, key):  # -> Any:
        ...

context = ...
