"""
This type stub file was generated by pyright.
"""

class AuthExpiredError(ConnectionError):
    def __str__(self) -> str: ...

class BaseUnauthError(ConnectionError):
    def __str__(self) -> str: ...
