"""
This type stub file was generated by pyright.
"""

import socketio

class SIO(socketio.Client): ...

class SocketIO:
    def __init__(self, base) -> None: ...
    def __str__(self) -> str: ...
    def on_update_dtable(self, data, index, *args):  # -> None:
        """Default is print received data
        You can overwrite this event
        """
        ...

    def on_new_notification(self, data, index, *args):  # -> None:
        """Default is print received data
        You can overwrite this event
        """
        ...

    def on(self, event, handler):  # -> None:
        ...
    def wait(self):  # -> None:
        ...
