# Generated by Django 5.2.5 on 2025-08-26 05:16

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="The main title or name of the item.", max_length=255
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, URL-friendly slug for the item.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("MUSICAL_WORK", "Musical Work"),
                            ("RECORDING", "Recording"),
                            ("BOOK", "Book"),
                        ],
                        editable=False,
                        help_text="The type of this item, set automatically by the subclass.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A free-text description of the item.",
                        null=True,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        help_text="The year of publication or creation. Use a negative number for BC years.",
                        null=True,
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The month of publication or creation (1-12).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The day of publication or creation (1-31).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="A denormalized date field, automatically set from year, month, and day for sorting.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "db_table": "item",
                "ordering": ["-date", "identifier"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esperoj.item",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="The subtitle of the book, if any.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "isbn_10",
                    models.CharField(
                        blank=True, help_text="The 10-digit ISBN.", max_length=10
                    ),
                ),
                (
                    "isbn_13",
                    models.CharField(
                        blank=True, help_text="The 13-digit ISBN.", max_length=13
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "db_table": "book",
            },
            bases=("esperoj.item",),
        ),
        migrations.CreateModel(
            name="MusicalWork",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esperoj.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Musical Work",
                "verbose_name_plural": "Musical Works",
                "db_table": "musical_work",
            },
            bases=("esperoj.item",),
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the collection.", max_length=512
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, URL-friendly slug for the collection.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A detailed description of the collection's scope and contents.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "db_table": "collection",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["identifier"], name="collection_identif_b59345_idx"
                    ),
                    models.Index(fields=["name"], name="collection_name_396613_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("COMPOSER", "Composer"),
                            ("LYRICIST", "Lyricist"),
                            ("ARTIST", "Artist"),
                            ("PRODUCER", "Producer"),
                            ("ENGINEER", "Engineer"),
                            ("AUTHOR", "Author"),
                            ("EDITOR", "Editor"),
                            ("TRANSLATOR", "Translator"),
                        ],
                        help_text="The role of the person in this contribution.",
                        max_length=20,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The item being contributed to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="esperoj.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribution",
                "verbose_name_plural": "Contributions",
                "db_table": "contribution",
                "ordering": ["item", "role"],
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="A user-defined, descriptive name for the file.",
                        max_length=255,
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        help_text="The total size of the file in bytes.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="The IANA media type (MIME type) of the file.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "md5",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The MD5 hash of the file content.",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "sha1",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The SHA1 hash of the file content.",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The SHA256 hash of the file content.",
                        max_length=64,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "db_table": "file",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("md5__isnull", False)),
                        fields=("md5",),
                        name="unique_md5_if_not_null",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("sha1__isnull", False)),
                        fields=("sha1",),
                        name="unique_sha1_if_not_null",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("sha256__isnull", False)),
                        fields=("sha256",),
                        name="unique_sha256_if_not_null",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FileReplica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "replica_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Fast Replica"),
                            ("backup", "Secondary Replica"),
                            ("archive", "Archive Replica"),
                        ],
                        help_text="The role or type of this replica (e.g., 'original', 'access_copy').",
                        max_length=50,
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(
                        choices=[
                            ("fast_ssd_storage", "Fast SSD"),
                            ("s3_archive_storage", "S3 Archive"),
                        ],
                        help_text="The configured storage backend where this replica is located.",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="The logical file that this replica is a copy of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replicas",
                        to="esperoj.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Replica",
                "verbose_name_plural": "File Replicas",
                "db_table": "file_replica",
                "ordering": ["file", "replica_type"],
            },
        ),
        migrations.CreateModel(
            name="FileBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block_order",
                    models.PositiveIntegerField(
                        help_text="The sequential position of this block within the replica (0-indexed)."
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="The full path or key of this block within the storage backend.",
                        max_length=1024,
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        help_text="The size of this individual block in bytes.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="The MIME type of the block, if different from the parent file.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "md5",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The MD5 hash of the block's content.",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "sha1",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The SHA1 hash of the block's content.",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The SHA256 hash of the block's content.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "replica",
                    models.ForeignKey(
                        help_text="The file replica that this block is a part of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="esperoj.filereplica",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Block",
                "verbose_name_plural": "File Blocks",
                "db_table": "file_block",
                "ordering": ["replica", "block_order"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBook",
            fields=[
                (
                    "item_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="esperoj.item",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid_utils.compat.uuid7, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "title",
                    models.CharField(
                        help_text="The main title or name of the item.", max_length=255
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, URL-friendly slug for the item.",
                        max_length=255,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("MUSICAL_WORK", "Musical Work"),
                            ("RECORDING", "Recording"),
                            ("BOOK", "Book"),
                        ],
                        editable=False,
                        help_text="The type of this item, set automatically by the subclass.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A free-text description of the item.",
                        null=True,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        help_text="The year of publication or creation. Use a negative number for BC years.",
                        null=True,
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The month of publication or creation (1-12).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The day of publication or creation (1-31).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="A denormalized date field, automatically set from year, month, and day for sorting.",
                        null=True,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="The subtitle of the book, if any.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "isbn_10",
                    models.CharField(
                        blank=True, help_text="The 10-digit ISBN.", max_length=10
                    ),
                ),
                (
                    "isbn_13",
                    models.CharField(
                        blank=True, help_text="The 13-digit ISBN.", max_length=13
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Book",
                "verbose_name_plural": "historical Books",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid_utils.compat.uuid7, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the collection.", max_length=512
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, URL-friendly slug for the collection.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A detailed description of the collection's scope and contents.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Collection",
                "verbose_name_plural": "historical Collections",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid_utils.compat.uuid7, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="A user-defined, descriptive name for the file.",
                        max_length=255,
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        help_text="The total size of the file in bytes.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="The IANA media type (MIME type) of the file.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "md5",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The MD5 hash of the file content.",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "sha1",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The SHA1 hash of the file content.",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The SHA256 hash of the file content.",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical File",
                "verbose_name_plural": "historical Files",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFileBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid_utils.compat.uuid7, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "block_order",
                    models.PositiveIntegerField(
                        help_text="The sequential position of this block within the replica (0-indexed)."
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="The full path or key of this block within the storage backend.",
                        max_length=1024,
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        help_text="The size of this individual block in bytes.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="The MIME type of the block, if different from the parent file.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "md5",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The MD5 hash of the block's content.",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "sha1",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The SHA1 hash of the block's content.",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The SHA256 hash of the block's content.",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replica",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The file replica that this block is a part of.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="esperoj.filereplica",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical File Block",
                "verbose_name_plural": "historical File Blocks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFileReplica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid_utils.compat.uuid7, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "replica_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Fast Replica"),
                            ("backup", "Secondary Replica"),
                            ("archive", "Archive Replica"),
                        ],
                        help_text="The role or type of this replica (e.g., 'original', 'access_copy').",
                        max_length=50,
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(
                        choices=[
                            ("fast_ssd_storage", "Fast SSD"),
                            ("s3_archive_storage", "S3 Archive"),
                        ],
                        help_text="The configured storage backend where this replica is located.",
                        max_length=50,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The logical file that this replica is a copy of.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="esperoj.file",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical File Replica",
                "verbose_name_plural": "historical File Replicas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid_utils.compat.uuid7, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "title",
                    models.CharField(
                        help_text="The main title or name of the item.", max_length=255
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, URL-friendly slug for the item.",
                        max_length=255,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("MUSICAL_WORK", "Musical Work"),
                            ("RECORDING", "Recording"),
                            ("BOOK", "Book"),
                        ],
                        editable=False,
                        help_text="The type of this item, set automatically by the subclass.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A free-text description of the item.",
                        null=True,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        help_text="The year of publication or creation. Use a negative number for BC years.",
                        null=True,
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The month of publication or creation (1-12).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The day of publication or creation (1-31).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="A denormalized date field, automatically set from year, month, and day for sorting.",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Item",
                "verbose_name_plural": "historical Items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMusicalWork",
            fields=[
                (
                    "item_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="esperoj.item",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid_utils.compat.uuid7, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "title",
                    models.CharField(
                        help_text="The main title or name of the item.", max_length=255
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, URL-friendly slug for the item.",
                        max_length=255,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("MUSICAL_WORK", "Musical Work"),
                            ("RECORDING", "Recording"),
                            ("BOOK", "Book"),
                        ],
                        editable=False,
                        help_text="The type of this item, set automatically by the subclass.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A free-text description of the item.",
                        null=True,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        help_text="The year of publication or creation. Use a negative number for BC years.",
                        null=True,
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The month of publication or creation (1-12).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The day of publication or creation (1-31).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="A denormalized date field, automatically set from year, month, and day for sorting.",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Musical Work",
                "verbose_name_plural": "historical Musical Works",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid_utils.compat.uuid7, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "authorized_name",
                    models.CharField(
                        help_text="The full, authoritative name in direct order (e.g., 'Dr. Martin Luther King, Jr.').",
                        max_length=512,
                    ),
                ),
                (
                    "sort_name",
                    models.CharField(
                        blank=True,
                        help_text="Name in inverted order for sorting (e.g., 'King, Martin Luther, Jr.'). Automatically generated if left blank.",
                        max_length=512,
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, human-readable identifier for this person.",
                        max_length=255,
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="The person's date of birth.", null=True
                    ),
                ),
                (
                    "death_date",
                    models.DateField(
                        blank=True, help_text="The person's date of death.", null=True
                    ),
                ),
                (
                    "biographical_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description or biographical information about the person.",
                    ),
                ),
                (
                    "wikipedia_link",
                    models.CharField(
                        blank=True,
                        help_text="A link to the person's Wikipedia page.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Person",
                "verbose_name_plural": "historical People",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid_utils.compat.uuid7, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the subject or topic.", max_length=512
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, URL-friendly slug for the subject.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A detailed description of the subject.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Subject",
                "verbose_name_plural": "historical Subjects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authorized_name",
                    models.CharField(
                        help_text="The full, authoritative name in direct order (e.g., 'Dr. Martin Luther King, Jr.').",
                        max_length=512,
                    ),
                ),
                (
                    "sort_name",
                    models.CharField(
                        blank=True,
                        help_text="Name in inverted order for sorting (e.g., 'King, Martin Luther, Jr.'). Automatically generated if left blank.",
                        max_length=512,
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, human-readable identifier for this person.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="The person's date of birth.", null=True
                    ),
                ),
                (
                    "death_date",
                    models.DateField(
                        blank=True, help_text="The person's date of death.", null=True
                    ),
                ),
                (
                    "biographical_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description or biographical information about the person.",
                    ),
                ),
                (
                    "wikipedia_link",
                    models.CharField(
                        blank=True,
                        help_text="A link to the person's Wikipedia page.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "db_table": "person",
                "ordering": ["sort_name"],
                "indexes": [
                    models.Index(
                        fields=["identifier"], name="person_identif_8bf926_idx"
                    ),
                    models.Index(
                        fields=["sort_name"], name="person_sort_na_8b3f07_idx"
                    ),
                    models.Index(
                        fields=["authorized_name"], name="person_authori_ebc142_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="people",
            field=models.ManyToManyField(
                blank=True,
                help_text="All people who contributed to this item.",
                related_name="items",
                through="esperoj.Contribution",
                to="esperoj.person",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid_utils.compat.uuid7, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("COMPOSER", "Composer"),
                            ("LYRICIST", "Lyricist"),
                            ("ARTIST", "Artist"),
                            ("PRODUCER", "Producer"),
                            ("ENGINEER", "Engineer"),
                            ("AUTHOR", "Author"),
                            ("EDITOR", "Editor"),
                            ("TRANSLATOR", "Translator"),
                        ],
                        help_text="The role of the person in this contribution.",
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The item being contributed to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="esperoj.item",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The person making the contribution.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="esperoj.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Contribution",
                "verbose_name_plural": "historical Contributions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="contribution",
            name="person",
            field=models.ForeignKey(
                help_text="The person making the contribution.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="esperoj.person",
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the subject or topic.", max_length=512
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, URL-friendly slug for the subject.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A detailed description of the subject.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "db_table": "subject",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["identifier"], name="subject_identif_95382f_idx"
                    ),
                    models.Index(fields=["name"], name="subject_name_f0356c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalRecording",
            fields=[
                (
                    "item_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="esperoj.item",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid_utils.compat.uuid7, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "title",
                    models.CharField(
                        help_text="The main title or name of the item.", max_length=255
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, URL-friendly slug for the item.",
                        max_length=255,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("MUSICAL_WORK", "Musical Work"),
                            ("RECORDING", "Recording"),
                            ("BOOK", "Book"),
                        ],
                        editable=False,
                        help_text="The type of this item, set automatically by the subclass.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A free-text description of the item.",
                        null=True,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        help_text="The year of publication or creation. Use a negative number for BC years.",
                        null=True,
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The month of publication or creation (1-12).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The day of publication or creation (1-31).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="A denormalized date field, automatically set from year, month, and day for sorting.",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The musical work that was performed in this recording.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="esperoj.musicalwork",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Recording",
                "verbose_name_plural": "historical Recordings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esperoj.item",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        help_text="The musical work that was performed in this recording.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recordings",
                        to="esperoj.musicalwork",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recording",
                "verbose_name_plural": "Recordings",
                "db_table": "recording",
            },
            bases=("esperoj.item",),
        ),
        migrations.AddIndex(
            model_name="filereplica",
            index=models.Index(
                fields=["file", "replica_type"], name="file_replic_file_id_d28c16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filereplica",
            index=models.Index(
                fields=["storage_name"], name="file_replic_storage_b52fa7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fileblock",
            unique_together={("replica", "block_order")},
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["-date", "identifier"], name="item_date_bef137_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["identifier"], name="item_identif_9b2dd9_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["title"], name="item_title_cd633e_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["item_type"], name="item_item_ty_abb93f_idx"),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("month__isnull", True), ("year__isnull", False), _connector="OR"
                ),
                name="month_requires_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("day__isnull", True), ("month__isnull", False), _connector="OR"
                ),
                name="day_requires_month",
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["person", "item", "role"], name="contributio_person__eb27d8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contribution",
            unique_together={("person", "item", "role")},
        ),
    ]
