# Generated by Django 5.2.5 on 2025-08-15 12:31

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esperoj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='esperoj_ite_title_4b2c22_idx',
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='sha1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcreator',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='sha1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfilestorage',
            name='sha1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfilestorage',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalsong',
            name='date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsong',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalsubject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['path'], name='esperoj_fil_path_a2e4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='filestorage',
            index=models.Index(fields=['file', 'storage_name'], name='esperoj_fil_file_id_fc0afa_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['title', 'date'], name='esperoj_ite_title_4cbcb8_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['languages'], name='esperoj_ite_languag_4ac758_gin'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('sha256__isnull', False)), fields=('sha256',), name='unique_sha256'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('sha1__isnull', False)), fields=('sha1',), name='unique_sha1'),
        ),
    ]
