# Generated by Django 5.2.5 on 2025-09-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esperoj", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filereplica",
            name="storage_name",
            field=models.CharField(
                choices=[
                    ("local_default", "Local Default Storage"),
                    ("catbox", "Catbox.moe"),
                    ("internetarchive", "Internet Archive"),
                    ("wayback_machine", "Wayback Machine"),
                ],
                help_text="The configured storage backend where this replica is located.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfilereplica",
            name="storage_name",
            field=models.CharField(
                choices=[
                    ("local_default", "Local Default Storage"),
                    ("catbox", "Catbox.moe"),
                    ("internetarchive", "Internet Archive"),
                    ("wayback_machine", "Wayback Machine"),
                ],
                help_text="The configured storage backend where this replica is located.",
                max_length=50,
            ),
        ),
    ]
