# Generated by Django 5.2.5 on 2025-08-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esperoj', '0002_remove_item_esperoj_ite_title_4b2c22_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbook',
            name='www',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='www',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsong',
            name='www',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='www',
            field=models.URLField(blank=True, null=True),
        ),
    ]
