# Generated by Django 5.2.5 on 2025-08-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esperoj', '0003_historicalbook_www_historicalitem_www_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbook',
            name='identifier',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='identifier',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalsong',
            name='identifier',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='identifier',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
