# Generated by Django 5.2.5 on 2025-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esperoj', '0005_alter_historicalbook_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbook',
            name='identifier',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='identifier',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalsong',
            name='identifier',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='identifier',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
