"""
This type stub file was generated by pyright.
"""

def convert_row(metadata, ws_data):  # -> Any | dict[Any, Any]:
    """Convert websocket row data to readable row data

    :param metadata: dict
    :param ws_data: str
    :return: dict
    """
    ...

def is_single_multiple_structure(
    column,
):  # -> tuple[Literal[True], Any | list[Any]] | tuple[Literal[False], list[Any]]:
    ...
def convert_db_rows(metadata, results):
    """Convert dtable-db rows data to readable rows data

    :param metadata: list
    :param results: list
    :return: list
    """
    ...
