name: Release Binary

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

defaults:
  run:
    shell: bash
    working-directory: ./projects/esperoj


jobs:
  release:
    if: github.server_url == 'https://github.com' && github.repository == 'esperoj/esperoj'
    runs-on: ${{ matrix.runner.name }}
    timeout-minutes: 60
    strategy:
      matrix:
        runner:
          - name: blacksmith
            arch: x86_64
          - name: blacksmith-arm
            arch: aarch64
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - uses: actions/setup-python@main
        with:
          python-version: "3.x"
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            requirements-nuitka.txt

      - name: Setup
        run: |
          pip install -r requirements-nuitka.txt
          pip install -e .[cli,server]
          cp esperoj/__main__.py .

      - uses: Nuitka/Nuitka-Action@main
        with:
          working-directory: "projects/esperoj"
          nuitka-version: main
          script-name: __main__.py
          output-dir: "build"

      - name: Change name
        run: |
          ls
          ls *
          mv build/__main__.bin ./esperoj_linux_${{ matrix.runner.arch }}
          rm __main__.py

      - name: Release
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            projects/esperoj/esperoj_linux_${{ matrix.runner.arch }}

      - name: Send notification
        env:
          NTFY_URL: ${{ secrets.NTFY_URL }}
          MY_UUID: ${{ secrets.MY_UUID }}
        if: ${{ always() }}
        run: |
          curl -fsLS https://codeberg.org/esperoj/dotfiles/raw/branch/main/bin/notify.sh | bash -s -- "" \
          "Title: Workflow ${{ github.workflow }} of ${{ github.repository }} completed" \
          "Actions: view, View log, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          | jq
