name: Release Binary

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

defaults:
  run:
    shell: bash
    working-directory: ./projects/esperoj

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - uses: actions/setup-python@main
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            requirements-nuitka.txt

      - name: Setup
        run: pip install -r requirements-nuitka.txt

      - uses: Nuitka/Nuitka-Action@main
        with:
          working-directory: "projects/esperoj/esperoj"
          nuitka-version: main
          script-name: __main__.py
          include-package: esperoj
          standalone: true
          onefile: true
          output-dir: "../build"

      - name: Change name
        run: |
          mv build/__main__.bin ./esperoj_linux_x86_64
          tar -czf esperoj_linux_x86_64.tar.gz -C build/__main__.dist .

      - name: Release
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            projects/esperoj/esperoj_linux_x86_64
            projects/esperoj/esperoj_linux_x86_64.tar.gz