name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: pip install --no-input poetry

      - name: Publish package
        run: |
          poetry config repositories.private "https://codeberg.org/api/packages/esperoj/pypi"
          poetry config http-basic.private "${{ secrets.POETRY_HTTP_BASIC_ESPEROJ_USERNAME }}" "${{ secrets.POETRY_HTTP_BASIC_ESPEROJ_PASSWORD }}"
          poetry publish --build --repository private
