name: Test

permissions:
  pull-requests: write

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'projects/esperoj/**'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./projects/esperoj


jobs:
  test:
    runs-on: ${{ vars.default_runner || 'ubuntu-latest' }}
    if: github.server_url == 'https://git.gay' && github.repository == 'esperoj/esperoj'
    container:
      image: esperoj/dotfiles:dev
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    name: Python ${{ matrix.python-version }}
    steps:

      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@master

      - name: Checkout
        uses: actions/checkout@main

      - name: Setup
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          export PATH="$HOME/.local/bin:$PATH"
          uv python pin ${{ matrix.python-version }}
          ENV=dev task setup

      - name: Test package
        run: task test

      - name: Send notification
        env:
          NTFY_URL: ${{ secrets.NTFY_URL }}
          MY_UUID: ${{ secrets.MY_UUID }}
        if: ${{ always() }}
        run: |
          curl -fsLS https://raw.githubusercontent.com/esperoj/dotfiles/refs/heads/main/bin/notify.sh | bash -s -- "" \
          "Title: Workflow ${{ github.workflow }} of ${{ github.repository }} completed" \
          "Actions: view, View log, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          | jq