name: Test

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: ./projects/esperoj

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    name: Python ${{ matrix.python-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install exiftool
        run: sudo apt-get install -qy exiftool

      - name: Install task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            ./requirements.txt
            ./requirements-test.txt

      - name: Install dependencies
        run: ENV=test task setup

      - name: Test package
        run: task test

